### ISSUE TITLE
Clarify statement around VCWG coordination re Normalization and Signatures

### ISSUE THREAD

**Issue by nadalin** [w3c-ccg/did-wg-charter#12]
"Verifiable Claims Working Group
Coordination on named graph indexing and other concerns regarding support for normalization and digital signatures"

Remove or reword as there is no normalization or signatures in VC WG, there should be no dependencies on VC for DID

**Comment by kimdhamilton** [comment]
Key concern is not requiring JSON-LD processor for JSON-only syntaxes

**Comment by nadalin** [comment]
@kimdhamilton and not pulling in unfinished/non-started standards like the LD-Signature and LD-C14N specs

**Comment by kimdhamilton** [comment]
What about something like this?

"Coordination on named graph indexing and other concerns in support of syntaxes/proof mechanisms requiring canonicalization, in a manner that does not impose burden (in the form of standards or libraries) if otherwise not required."

(Sorry that it's awkward, I'm still learning)

@burnburn @msporny @nadalin

**Comment by nadalin** [comment]
@kimdhamilton I can't parse that to tell if proof mechanisms are in or out of scope as it sounds like they are as long as you don't burden them with C14N, is that right?

**Comment by nadalin** [comment]
"Coordination on named graph indexing and other concerns regarding support for normalization and digital signatures." the VCWG is not working on normalizations and signatures as that is out of scope for that WG I was told. So I would leave it at "Coordination on named graph indexing."

**Comment by msporny** [comment]
The group discussed this on the 2019-06-27 call and agreed that we should remove the language, primarily because the Verifiable Claims Working Group will not exist by the time the DID WG starts. The group also identified that we should have more groups listed in this section and will raise another issue to ensure that we have more groups listed so that it is easier to understand where this work fits in relation to other work in this area.

**Comment by msporny** [comment]
Removed reference to W3C Verifiable Claims WG in this commit: https://github.com/w3c-ccg/did-wg-charter/commit/0b05193fdbfc81929558652ab8120c4c0d255faa

**Comment by msporny** [comment]
New issue raised for making coordination section better: https://github.com/w3c-ccg/did-wg-charter/issues/44

**Comment by msporny** [comment]
We discussed this on the 2019-06-27 call, made the changes above, and the group agreed that we have addressed this issue. Closing.
