### ISSUE TITLE
Normative Specifications 

### ISSUE THREAD

**Issue by nadalin** [w3c-ccg/did-wg-charter#33]
"The Credentials Community Group has developed a Final Community Group Specification for Decentralized Identifiers that has been shipped in multiple production-grade commercial systems that will serve as input for this document."

We should be starting with a set of requirements not a specification, that can follow, if the proposed specification has a set of requirements these should be listed in the charter by a normative document of some sort, if not then a proposed specification without requirements is not really useful

**Comment by kimdhamilton** [comment]
5/16/2019 proposal: convert [DID Actions](https://w3c-ccg.github.io/did-use-cases/#did-actions) to requirements

**Comment by msporny** [comment]
Agree that we should rename "DID Actions" to "Decentralized Identifier Requirements", and then note that the requirements can be discussed as actions that are contemplated to be supported by the ecosystem. This will require a PR to the DID Use Cases document.

No change is required to the DID WG Charter since it references Decentralized Identifier Use Cases v1.0. The Use Cases document doesn't have to be normative as use cases and requirements are typically treated as guiding principles, not hard technical specifications.

* [x] Update DID Use Cases document to mention "[Required Features](https://w3c-ccg.github.io/did-use-cases/#features)" and point to that from the DID WG Charter.
* [ ] Close this issue.

**Comment by jandrieu** [comment]
There is a category error here.

The DID Action section is a list of actions you can do with DIDs. It is NOT, as such, a list of requirements, but merely a listing of supported actions.

Rather, from the Use Case document, it is actually the Features set that is a more complete set of requirements for DIDs.

I believe Kim's suggestion was to do something like we did in the VC-data-model spec, which is to distill from the use case document a set of requirements that could be included in a non-normative section of the spec.

Such a set of requirements should be based on the Features, IMO, and not on the Actions section. Further, I think the PR should be on the did-spec (which should reference the use cases), not the use case document itself.

**Comment by jandrieu** [comment]
Added PR with link to "Required Features" section of the use case document. 
https://github.com/w3c-ccg/did-wg-charter/pull/54

**Comment by msporny** [comment]
We discussed this on the 2019-07-02 call and the group agreed to reference the required features section of the use cases document from the charter.
