### ISSUE TITLE
self-sovereign

### ISSUE THREAD

**Issue by nadalin** [w3c-ccg/did-wg-charter#35]
"Decentralized Identifiers (DIDs) are a new type of identifier for verifiable, "self-sovereign" digital identity."

I would remove "self-sovereign" and leave it at decentralized as we had a discussion in ISO last week about this and consensus from national bodies was this was not well understood and limiting

**Comment by msporny** [comment]
The group discussed this on the 2019-06-27 call. We merged PR #38 to remove the term "self-sovereign" from the introductory text. We have opened a new issue #46 to point to the self-sovereign identity principles as an input to the Working Group. Closing.

**Comment by nadalin** [comment]
@msporny Are the Principles being submitted as part of charter? If not then this might be an issue since I don't know the purpose of pointing to them or how we would input to them as part of the charter

**Comment by msporny** [comment]
> @msporny Are the Principles being submitted as part of charter? 

They are being referenced in the Charter so that they are used as an input document to the WG.

> If not then this might be an issue since I don't know the purpose of pointing to them or how we would input to them as part of the charter

It's the same as pointing to a use cases document as *one* of the inputs to the WG. It provides guidance to the WG that the "self-sovereign identity principles" document is something that the WG should consider when refining the specification, but it does not necessarily insist that the document itself is refined by the WG. So the WG may include some of those principles in the design, or none of them, but it does signal what the expectations on the WG are in a more clear manner than just saying "self-sovereign".
